name: Provision and Deploy via CodeWorks Infra

inputs:
  host:
    required: true
  ssh_key:
    required: true
  ghcr_pat:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run provision and deploy script
      shell: bash
      run: |
        bash "${{ github.action_path }}/provision_and_deploy.sh" \
          "${{ inputs.host }}" \
          "${{ inputs.ssh_key }}" \
          "${{ inputs.ghcr_pat }}"
